### ISSUE TITLE
txtScoreRam ?

### ISSUE THREAD

**Issue by malbanGit** [b-mag/suckshoot#1]
```
     ORG $c880       ; well start of our ram space

;txtScoreRam DS 100


     ;ORG $c980
      ORG $c900
```

Why did you comment the above out an put txtScoreRam into ROM space?

As it is this will not work on a Vectrex.
In Vide it might work if you have ROM write access enabled - but you should not do that.
(That option is for "special" cartridges, which have additional RAM space or can write FLASH memory.

**Comment by b-mag** [comment]
Merging corrected version now.  I believe when I adapted his project into vide project I mixed up some variables but it appeared to mostly work.
